name       = "Fiats-Demonstration-Applications"
license    = "(Please see fiats/LICENSE.txt.)"
author     = "(Please see fiats/fpm.toml.)"
maintainer = "(Please see fiats/fpm.toml.)"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.7.0"}
julienne = {git = "https://github.com/berkeleylab/julienne", tag = "1.2.2"}
fiats = {path = "../"}
netcdf-interfaces = {git = "https://github.com/LKedward/netcdf-interfaces.git", rev = "d2bbb71ac52b4e346b62572b1ca1620134481096"}
