name: Build with LLVM-Flang

on: [push, pull_request]


jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: true
    container: gmao/llvm-flang:latest
    env:
      FC: flang-new
      CC: clang

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test
      if: contains(matrix.os, 'ubuntu')
      run: |
        fpm --version
        export FPM_FC=$FC
        export FPM_CC=$CC
        fpm test --flag "-mmlir -allow-assumed-rank -O3"
